/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs262Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.*;

/**
 *
 * @author anilaswani
 */
public class placeOrder extends javax.swing.JFrame {

    /**
     * Creates new form placeOrder
     */
    public placeOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        orderButton = new javax.swing.JButton();
        walletButton = new javax.swing.JButton();
        placeOrderButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        usernameTf = new javax.swing.JTextField();
        medBox1 = new javax.swing.JComboBox();
        medBox2 = new javax.swing.JComboBox();
        medBox3 = new javax.swing.JComboBox();
        quantityTf2 = new javax.swing.JTextField();
        passwordTf = new javax.swing.JPasswordField();
        quantityTf1 = new javax.swing.JTextField();
        quantityTf3 = new javax.swing.JTextField();
        addressToDeliverTf = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        orderItemButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(255, 0, 51));

        orderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs262project/order.png"))); // NOI18N
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        walletButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs262project/wallet.png"))); // NOI18N
        walletButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletButtonActionPerformed(evt);
            }
        });

        placeOrderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs262project/shopping-bag.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(walletButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(placeOrderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(walletButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(placeOrderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 51));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLACE ORDER");

        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs262project/logout.png"))); // NOI18N
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(logoutButton))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 0, 51));

        usernameTf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        usernameTf.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "USERNAME"));

        medBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MEDICINE NAME", "CROCIN", "DOLOPAR", "PARACETAMOL", "BENADRYL", "DVN_Forte", "ORS" }));
        medBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medBox1ActionPerformed(evt);
            }
        });

        medBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MEDICINE NAME", "CROCIN", "DOLOPAR", "PARACETAMOL", "BENADRYL", "DVN_Forte", "ORS" }));

        medBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MEDICINE NAME", "CROCIN", "DOLOPAR", "PARACETAMOL", "BENADRYL", "DVN_Forte", "ORS" }));

        quantityTf2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityTf2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Quantity"));
        quantityTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTf2ActionPerformed(evt);
            }
        });

        passwordTf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        passwordTf.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Password"));

        quantityTf1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityTf1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Quantity"));
        quantityTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTf1ActionPerformed(evt);
            }
        });

        quantityTf3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        quantityTf3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Quantity"));
        quantityTf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTf3ActionPerformed(evt);
            }
        });

        addressToDeliverTf.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addressToDeliverTf.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Addtress To Deliver"));
        addressToDeliverTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressToDeliverTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressToDeliverTf)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(medBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(medBox1, 0, 200, Short.MAX_VALUE)
                            .addComponent(usernameTf))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityTf2)
                            .addComponent(passwordTf)
                            .addComponent(quantityTf1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(medBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityTf3)
                        .addGap(5, 5, 5)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameTf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressToDeliverTf, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTf1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(medBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTf2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(medBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTf3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs262project/man (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        orderItemButton.setBackground(new java.awt.Color(255, 51, 51));
        orderItemButton.setForeground(new java.awt.Color(51, 51, 51));
        orderItemButton.setText("PLACE ORDER");
        orderItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderItemButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(orderItemButton, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderItemButton)
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        myOrders t1 = new myOrders();
        t1.setVisible(true);
    }//GEN-LAST:event_orderButtonActionPerformed

    private void walletButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        wallet t1 = new wallet();
        t1.setVisible(true);
    }//GEN-LAST:event_walletButtonActionPerformed

    private void orderItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderItemButtonActionPerformed
        // TODO add your handling code here:
        if (usernameTf.getText().isEmpty() || passwordTf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "First Enter USERNAME and PASSWORD both.");
        } else {
            try {
                //assuming we are only three medicines at a time
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pharmacy?autoReconnect=true&useSSL=false", "root", "#Av2002Gs");

                String username = usernameTf.getText();
                String password = passwordTf.getText();
                boolean exist;

                PreparedStatement ps = con.prepareStatement("select Username, Password from pharmacy.customer where Username = ? and Password = ?;");
                ps.setString(1, username);
                ps.setString(2, password);

                try (ResultSet resultSet = ps.executeQuery()) {
                    exist = resultSet.next();
                }

                if (exist) {
                    String med1 = medBox1.getSelectedItem().toString();
                    String med2 = medBox2.getSelectedItem().toString();
                    String med3 = medBox3.getSelectedItem().toString();
                    int q1 = Integer.parseInt(quantityTf1.getText());
                    int q2 = Integer.parseInt(quantityTf2.getText());
                    int q3 = Integer.parseInt(quantityTf3.getText());

                    String amountQuery1 = "select PricePerPiece from pharmacy.product where ProductId in (select "
                            + "Productid from pharmacy.medicines where Name = '" + med1 + "');";
                    Statement stmt = con.createStatement();
                    ResultSet rSet = stmt.executeQuery(amountQuery1);
                    rSet.next();
                    int price1 = rSet.getInt("PricePerPiece");

                    String amountQuery2 = "select PricePerPiece from pharmacy.product where ProductId in (select "
                            + "Productid from pharmacy.medicines where Name = '" + med2 + "');";
                    Statement stmt2 = con.createStatement();
                    ResultSet rSet2 = stmt2.executeQuery(amountQuery2);
                    rSet2.next();
                    int price2 = rSet2.getInt("PricePerPiece");

                    String amountQuery3 = "select PricePerPiece from pharmacy.product where ProductId in (select "
                            + "Productid from pharmacy.medicines where Name = '" + med3 + "');";
                    Statement stmt3 = con.createStatement();
                    ResultSet rSet3 = stmt3.executeQuery(amountQuery3);
                    rSet3.next();
                    int price3 = rSet3.getInt("PricePerPiece");

                    String query = "select * from pharmacy.order";
                    Statement st = con.createStatement();
                    ResultSet rs = st.executeQuery(query);
                    int orderID = 0;

                    while (rs.next()) {
                        orderID = rs.getInt(1);
                    }

                    int amountFinal = q1 * price1 + q2 * price2 + q3 * price3;
                    String addressDelivery = addressToDeliverTf.getText();

                    String query2 = "INSERT INTO `pharmacy`.`order` (`OrderId`, `OrderDate`, `ExpectedDeliveryDate`, `BillingAmount`, `AddressToDeliver`, `ShippingStatus`, `Username`) "
                            + "VALUES (?, ?, ?, ?, ?, ?, ?);";
                    
                    PreparedStatement pst = con.prepareStatement(query2);

                    pst.setInt(1, orderID + 1);
                    pst.setDate(2, java.sql.Date.valueOf("2022-04-22"));
                    pst.setDate(3, java.sql.Date.valueOf("2022-05-01"));
                    pst.setInt(4, amountFinal);
                    pst.setString(5, addressDelivery);
                    pst.setString(6, "OrderPlaced");
                    pst.setString(7, username);
                    
                    pst.execute();

                    String prescriptionQuery1 = "select isPrescriptionRequired from pharmacy.medicines where Name = '" + med1 + "';";
                    Statement stmt4 = con.createStatement();
                    ResultSet rSet4 = stmt4.executeQuery(prescriptionQuery1);
                    rSet4.next();
                    int prescription1 = rSet4.getInt("isPrescriptionRequired");

                    String prescriptionQuery2 = "select isPrescriptionRequired from pharmacy.medicines where Name = '" + med2 + "';";
                    Statement stmt5 = con.createStatement();
                    ResultSet rSet5 = stmt5.executeQuery(prescriptionQuery2);
                    rSet5.next();
                    int prescription2 = rSet5.getInt("isPrescriptionRequired");

                    String prescriptionQuery3 = "select isPrescriptionRequired from pharmacy.medicines where Name = '" + med3 + "';";
                    Statement stmt6 = con.createStatement();
                    ResultSet rSet6 = stmt6.executeQuery(prescriptionQuery3);
                    rSet6.next();
                    int prescription3 = rSet6.getInt("isPrescriptionRequired");
                                        
                    int medId1 = 0;
                    int medId2 = 0;
                    int medId3 = 0;

                    String query3 = "select Productid from pharmacy.medicines where Name = '" + med1 + "';";
                    Statement st2 = con.createStatement();
                    ResultSet rs2 = st2.executeQuery(query3);
                    rs2.next();
                    medId1 = rs2.getInt("Productid");
    

                    String finalQuery1 = "INSERT INTO `pharmacy`.`order_product_relationship` (`OrderId`, `ProductId`, `Quantity`) "
                            + "VALUES (?, ?, ?);";
                    PreparedStatement pst2 = con.prepareStatement(finalQuery1);

                    pst2.setInt(1, orderID + 1);
                    pst2.setInt(2, medId1);
                    pst2.setInt(3, q1);
                    pst2.execute();

                    String query4 = "select Productid from pharmacy.medicines where Name = '" + med2 + "';";
                    Statement st3 = con.createStatement();
                    ResultSet rs3 = st3.executeQuery(query4);
                    rs3.next();
                    medId2 = rs3.getInt("Productid");

                    String finalQuery2 = "INSERT INTO `pharmacy`.`order_product_relationship` (`OrderId`, `ProductId`, `Quantity`) "
                            + "VALUES (?, ?, ?);";
                    PreparedStatement pst3 = con.prepareStatement(finalQuery2);

                    pst3.setInt(1, orderID + 1);
                    pst3.setInt(2, medId2);
                    pst3.setInt(3, q2);
                    pst3.execute();

                    String query5 = "select Productid from pharmacy.medicines where Name = '" + med3 + "';";
                    Statement st4 = con.createStatement();
                    ResultSet rs4 = st4.executeQuery(query5);
                    rs4.next();
                    medId3 = rs4.getInt("Productid");

                    String finalQuery3 = "INSERT INTO `pharmacy`.`order_product_relationship` (`OrderId`, `ProductId`, `Quantity`) "
                            + "VALUES (?, ?, ?);";
                    PreparedStatement pst4 = con.prepareStatement(finalQuery3);

                    pst4.setInt(1, orderID + 1);
                    pst4.setInt(2, medId3);
                    pst4.setInt(3, q3);
                    pst4.execute();

                    usernameTf.setText("");
                    passwordTf.setText("");
                    quantityTf1.setText("");
                    quantityTf2.setText("");
                    quantityTf3.setText("");
                    addressToDeliverTf.setText("");
                    
                    if((prescription1  == 1) || (prescription2  == 1) || (prescription3  == 1) ){
                        JOptionPane.showMessageDialog(this, "Order Placed with Final Billing Amount to be paid of Rs. " + amountFinal + " and "
                                + "Please show prescription at the time of delivery.");

                    }else{
                        JOptionPane.showMessageDialog(this, "Order Placed with Final Billing Amount to be paid of Rs. " + amountFinal + "");

                    }
                    
                    
                } else {

                    JOptionPane.showMessageDialog(this, "USERNAME OR PASSWORD IS WRONG!!");
                    usernameTf.setText("");
                    passwordTf.setText("");
                    quantityTf1.setText("");
                    quantityTf2.setText("");
                    quantityTf3.setText("");
                    addressToDeliverTf.setText("");

                }

                con.close();

            } catch (Exception e) {
                System.out.println(e);
            }

        }

    }//GEN-LAST:event_orderItemButtonActionPerformed

    private void medBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medBox1ActionPerformed

    private void quantityTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTf2ActionPerformed

    private void quantityTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTf1ActionPerformed

    private void quantityTf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTf3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTf3ActionPerformed

    private void addressToDeliverTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressToDeliverTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressToDeliverTfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(placeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(placeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(placeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(placeOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new placeOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressToDeliverTf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton logoutButton;
    private javax.swing.JComboBox medBox1;
    private javax.swing.JComboBox medBox2;
    private javax.swing.JComboBox medBox3;
    private javax.swing.JButton orderButton;
    private javax.swing.JButton orderItemButton;
    private javax.swing.JPasswordField passwordTf;
    private javax.swing.JButton placeOrderButton;
    private javax.swing.JTextField quantityTf1;
    private javax.swing.JTextField quantityTf2;
    private javax.swing.JTextField quantityTf3;
    private javax.swing.JTextField usernameTf;
    private javax.swing.JButton walletButton;
    // End of variables declaration//GEN-END:variables
}
